{% set version = "1.5.0" %}

package:
  name: django-rest-hooks
  version: {{ version }}

source:
  fn: django-rest-hooks-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/django-rest-hooks/django-rest-hooks-{{ version }}.tar.gz
  sha256: 26ec5537d70aee00b5562f32e2a092fbd19ed320c1adba5f180912d76aacaeab

build:
  script: python setup.py install
  number: 0

requirements:
  build:
    - python
    - django >=1.4
    - requests

  run:
    - python
    - django >=1.4
    - requests

test:
  imports:
    - rest_hooks

about:
  home: http://github.com/zapier/django-rest-hooks
  license: BSD 3-Clause
  summary: A powerful mechanism for sending real time API notifications via a new subscription model.

extra:
  recipe-maintainers:
    - Korijn
    - IvoFlipse
    - Maxyme
