travis:
  secure:
    BINSTAR_TOKEN: JSLxJAdLelfJ6O0Enp8YocivJuo/ZMt5Vem5xSRbG8Lplr8/16SgQ4I6GG7SMVLYoEdVnRllJCnAl2gbCJ0M6T4k9gO9TJ/sEEsTR4ftfXJt9qwwllNOsp5rcwYC9gqlkgM3ZKHwr8VY7CVtdlmewo+206qaixob01AYOEAo8Zsj0NGcWBTPT3WczxLR4quYBZLs3j81rDCPOsnj2JT272GyXme8fib4Rv9WXHxSvU1XdipA1ruGK0hQSg91o+7Hr53UeSxUjeEubhrO48fTjGiTPHZQLNQ0EUINZT11Uqlea3e8EuCO1idrmw3TMK20T5uiYm0BInZK3dVC2ASF+84cWLYLXL2AhxHPz74vuyrTKfBINgbanIsBRaeZChHJqpzHpVQrnKJl/4cX+5Jgh1wTkn9wn+SolZg51X0cDxcdw+lPmkVqM3kthjKvnWWmt3NJdzqC9GRIS25qV1+5/nBOXJ4lf798Wnss5gBeJB4tzoAreZmx8Y/Fcf2AslBiwNkhn4rldCktHRYXWnneBwQnKE/Z2DPf4ttYx2jym8/qIAAAN4HmAtWZkZZIoolDezPELElwEHPoCQI4JSUgrEfrh6Zqta/L26wrCRUj//pVZZOowY2Ju5dLPsVhp/n9OiIehdNRcWWiuEBykVECwxK941A1YeK6bceaze0HMjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
